### ISSUE TITLE
Export sketches

### ISSUE THREAD

**Issue by fstiffo** [Sketch-sh/sketch-sh#172] opened 2018-09-04 17:44 UTC
An export feature (of the code at least) would be appreciated, losing code is always hard. 

thx in advance

**Comment by fstiffo** [comment] 2018-09-04 18:03
Sorry I closed a previous request with the same argument by mistake. The possibility to download the sketch as a text file or 2 (markdown and code). No, I didn't loose any code.

**Comment by thangngoc89** [comment] 2018-09-04 18:07
@fstiffo then this is an duplicate of #41

**Closed by thangngoc89** 2018-09-04 18:07 UTC
